# Generated by Django 4.2 on 2023-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_fingerprints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna', models.CharField(max_length=255)),
            ],
        ),
    ]
