# Generated by Django 4.2 on 2023-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_dna_delete_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dna',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
