# Generated by Django 4.2 on 2023-08-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_dna_member_cr_dna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cr_dna',
        ),
    ]
